name: Build Executables

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        config:
          - triple: x86_64-pc-windows-msvc
            os: windows-latest
            exe_suffix: .exe
    runs-on: ${{ matrix.config.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ matrix.config.target }}
    - name: Build
      run: cargo build --release --target ${{ matrix.config.target }}
    - name: Upload a Build Artifact (exe)
      uses: actions/upload-artifact@v4.6.1
      with:
        name: executable_${{ matrix.config.target }}
        path: target/${{ matrix.config.target }}/release/turtly-converter${{ matrix.config.exe_suffix }}
